[workspace]
members = ["macros", "log"]

[package]
name = "effie"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Matilde Morrone <contact@matilde.pet>"]
description = "Idiomatic api to uefi"
documentation = "https://docs.rs/effie"
repository = "https://github.com/tailwags/effie"
include = ["src/**/*.rs", "README.md", "LICENSE"]
readme = "README.md"

[features]
serde = ["dep:serde_core"]
log = ["dep:log"]

[dependencies]
bitflags = "2.13.0"
effie-macros = { version = "0.1.0", path = "macros" }
log = { version = "0.4", default-features = false, optional = true }
serde_core = { version = "1.0.228", default-features = false, optional = true }
